### PR TITLE
Fix `rake db:dev_seed` task flaky spec

### LINKED ISSUE #1197: Flaky spec:  undefined method `selected?' at rake db:dev_seed
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 6200

**Failure:**

```
  1) rake db:dev_seed seeds the database without errors
     Failure/Error: expect { run_rake_task }.not_to raise_error
       expected no Exception, got #<NoMethodError: undefined method `selected?' for nil:NilClass> with backtrace:
         # ./app/models/budget/ballot/line.rb:31:in `check_selected'
         # ./app/models/budget/ballot.rb:12:in `add_investment'
         # ./db/dev_seeds.rb:540:in `block (2 levels) in <top (required)>'
         # ./db/dev_seeds.rb:537:in `times'
         # ./db/dev_seeds.rb:537:in `block in <top (required)>'
         # ./db/dev_seeds.rb:10:in `section'
         # ./db/dev_seeds.rb:536:in `<top (required)>'
         # ./lib/tasks/db.rake:4:in `block (2 levels) in <top (required)>'
         # ./spec/lib/tasks/dev_seed_spec.rb:12:in `block (2 levels) in <top (required)>'
         # ./spec/lib/tasks/dev_seed_spec.rb:16:in `block (3 levels) in <top (required)>'
         # ./spec/lib/tasks/dev_seed_spec.rb:16:in `block (2 levels) in <top (required)>'
     # ./spec/lib/tasks/dev_seed_spec.rb:16:in `block (2 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

### PR DESCRIPTION
**Pull request by aitbw**
Where
=====
* **Related issue:** #1197 (This PR closes #1197 once merged)

What
====
* Added missing `require` statements needed for the spec to work properly
* Removed extra `end` that was causing the test to fail
* Mitigated scenario where the `rake db:dev_seed` task spec would fail if a randomly selected budget had no investments associated with it under the `Balloting Investments` seeding section

How
===
* The problem was that the budget selected randomly under the `Balloting Investments` section could not have investments associated with it, so when an investment of said budget was to be added to a ballot, the `Budget::Ballot::Line#check_selected` validation failed since the `selected?` method was not available to a `NilClass` element

* The proposed PR takes as inspiration the `Balloting Investments` section of the `dev_seeds` [file](https://github.com/consul/consul/blob/master/db/dev_seeds.rb#L396) found in CONSUL to select **only** finished budgets as a method to mitigate said flaky test

Test
====
* Fixed coverage ✅

### CODE REVIEW

File: db/dev_seeds.rb [hunk 1]
```diff
@@ -481,26 +481,26 @@ def unique_document_number
...
   Budget.create(
     name: "Budget #{Date.current.year}",
     currency_symbol: "€",
     phase: 'accepting'
   )
 
-    (1..([1, 2, 3].sample)).each do |i|
-      group = budget.groups.create!(name: "#{Faker::StarWars.planet} #{i}")
+  (1..([1, 2, 3].sample)).each do |i|
+    group = budget.groups.create!(name: "#{Faker::StarWars.planet} #{i}")
```
Comment (bertocq) [inline db/dev_seeds.rb]: We need groups for both Budgets, not just for the finished one only

Comment (aitbw) [reply db/dev_seeds.rb]: Would something like [this](https://gist.github.com/aitbw/f092ecfd990827ce77f8516a29e02ab1) work?

Comment (bertocq) [reply db/dev_seeds.rb]: I just realized on consul we've a refactor that creates more "descriptive" geozones

Comment (aitbw) [reply db/dev_seeds.rb]: Hmm 🤔 how should we proceed, then?

Comment (bertocq) [reply db/dev_seeds.rb]: No problem just that solution will do nice for madrid right now, fixing dev_seeds with "realistic" or "descriptive" content is going to be a long task full of small improvements... best way would be to just on every new feature, increase dev_seeds, as well as everytime we revisit something.. clean related dev_seeds if possible... But for now just that solution 🆗  and we can continue with everything else at madrid :) 👏

Comment (aitbw) [reply db/dev_seeds.rb]: Great, @bertocq! Amending right away :)

**Comment by voodoorai2000** [comment]
Awesome 🎉 
Appreciate it @aitbw :)
